import json


def json_res():
    return [
        {
            "annualCost": 1646.34,
            "annualSaving": -768.71,
            "annualSavingPercentage": -87.6,
            "annualStandingChargeElec": 13721.4,
            "annualStandingChargeGas": 7446.6,
            "contractLength": 12,
            "energySwitchGuarantee": False,
            "exitPenaltyAmount": 0.0,
            "saleable": False,
            "supplierName": "Outfox the Market",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 12,
            "tariffEndDateType": "R",
            "tariffName": "Fix'd 24 4.0",
            "unitPriceElec": 25.866,
            "unitPriceGas": 5.705,
            "warmHomeDiscount": False
        },
        {
            "annualCost": 1678.45,
            "annualSaving": -800.82,
            "annualSavingPercentage": -91.2,
            "annualStandingChargeElec": 18679.5,
            "annualStandingChargeGas": 11539.5,
            "contractLength": 12,
            "energySwitchGuarantee": True,
            "exitPenaltyAmount": 150.0,
            "saleable": False,
            "supplierName": "EDF Energy",
            "tariffEndDatePeriodFixed": "2025-03-31",
            "tariffEndDatePeriodRolling": 0,
            "tariffEndDateType": "F",
            "tariffName": "EDF Essentials 1Yr Mar25v3",
            "unitPriceElec": 23.856,
            "unitPriceGas": 5.704,
            "warmHomeDiscount": True
        },
        {
            "annualCost": 1693.75,
            "annualSaving": -816.12,
            "annualSavingPercentage": -93.0,
            "annualStandingChargeElec": 18902.1,
            "annualStandingChargeGas": 10800.3,
            "contractLength": 14,
            "energySwitchGuarantee": False,
            "exitPenaltyAmount": 150.0,
            "saleable": False,
            "supplierName": "ScottishPower",
            "tariffEndDatePeriodFixed": "2025-05-31",
            "tariffEndDatePeriodRolling": 0,
            "tariffEndDateType": "F",
            "tariffName": "Exclusive Help Beat Cancer Flexi May 2025 SM1 Online",
            "unitPriceElec": 22.885,
            "unitPriceGas": 6.109,
            "warmHomeDiscount": True
        },
        {
            "annualCost": 1709.02,
            "annualSaving": -831.39,
            "annualSavingPercentage": -94.7,
            "annualStandingChargeElec": 18905.25,
            "annualStandingChargeGas": 10803.45,
            "contractLength": -1,
            "energySwitchGuarantee": False,
            "exitPenaltyAmount": 0.0,
            "saleable": False,
            "supplierName": "Home Energy",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 0,
            "tariffEndDateType": " ",
            "tariffName": "Home SVT Feb 2024 v1",
            "unitPriceElec": 25.095,
            "unitPriceGas": 5.702,
            "warmHomeDiscount": False
        },
        {
            "annualCost": 1727.79,
            "annualSaving": -850.16,
            "annualSavingPercentage": -96.9,
            "annualStandingChargeElec": 18430.65,
            "annualStandingChargeGas": 11290.65,
            "contractLength": 12,
            "energySwitchGuarantee": True,
            "exitPenaltyAmount": 0.0,
            "saleable": False,
            "supplierName": "Octopus Energy",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 12,
            "tariffEndDateType": "R",
            "tariffName": "Octopus 12M Fixed February 2024 v3",
            "unitPriceElec": 24.665,
            "unitPriceGas": 5.961,
            "warmHomeDiscount": True
        },
        {
            "annualCost": 1732.33,
            "annualSaving": -854.7,
            "annualSavingPercentage": -97.4,
            "annualStandingChargeElec": 18679.5,
            "annualStandingChargeGas": 11539.5,
            "contractLength": 24,
            "energySwitchGuarantee": True,
            "exitPenaltyAmount": 250.0,
            "saleable": False,
            "supplierName": "EDF Energy",
            "tariffEndDatePeriodFixed": "2026-03-31",
            "tariffEndDatePeriodRolling": 0,
            "tariffEndDateType": "F",
            "tariffName": "EDF Essentials 2Yr Mar26v3",
            "unitPriceElec": 24.654,
            "unitPriceGas": 5.96,
            "warmHomeDiscount": True
        },
        {
            "annualCost": 1732.76,
            "annualSaving": -855.13,
            "annualSavingPercentage": -97.4,
            "annualStandingChargeElec": 18679.5,
            "annualStandingChargeGas": 11539.5,
            "contractLength": -1,
            "energySwitchGuarantee": True,
            "exitPenaltyAmount": 0.0,
            "saleable": False,
            "supplierName": "EDF Energy",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 0,
            "tariffEndDateType": " ",
            "tariffName": "Standard (Variable)",
            "unitPriceElec": 24.665,
            "unitPriceGas": 5.961,
            "warmHomeDiscount": True
        },
        {
            "annualCost": 1737.14,
            "annualSaving": -859.51,
            "annualSavingPercentage": -97.9,
            "annualStandingChargeElec": 18902.1,
            "annualStandingChargeGas": 10800.3,
            "contractLength": 14,
            "energySwitchGuarantee": False,
            "exitPenaltyAmount": 150.0,
            "saleable": False,
            "supplierName": "ScottishPower",
            "tariffEndDatePeriodFixed": "2025-05-31",
            "tariffEndDatePeriodRolling": 0,
            "tariffEndDateType": "F",
            "tariffName": "Help Beat Cancer Flexi May 2025 TM1 Online",
            "unitPriceElec": 23.625,
            "unitPriceGas": 6.292,
            "warmHomeDiscount": True
        },
        {
            "annualCost": 1743.21,
            "annualSaving": -865.58,
            "annualSavingPercentage": -98.6,
            "annualStandingChargeElec": 18851.7,
            "annualStandingChargeGas": 11682.3,
            "contractLength": 15,
            "energySwitchGuarantee": True,
            "exitPenaltyAmount": 150.0,
            "saleable": False,
            "supplierName": "British Gas",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 15,
            "tariffEndDateType": "R",
            "tariffName": "Price Promise",
            "unitPriceElec": 25.12,
            "unitPriceGas": 5.912,
            "warmHomeDiscount": True
        },
        {
            "annualCost": 1743.21,
            "annualSaving": -865.58,
            "annualSavingPercentage": -98.6,
            "annualStandingChargeElec": 18851.7,
            "annualStandingChargeGas": 11682.3,
            "contractLength": 14,
            "energySwitchGuarantee": True,
            "exitPenaltyAmount": 150.0,
            "saleable": False,
            "supplierName": "British Gas",
            "tariffEndDatePeriodFixed": "2025-05-31",
            "tariffEndDatePeriodRolling": 0,
            "tariffEndDateType": "F",
            "tariffName": "Price Promise May25",
            "unitPriceElec": 25.12,
            "unitPriceGas": 5.912,
            "warmHomeDiscount": True
        },
        {
            "annualCost": 1759.12,
            "annualSaving": -881.49,
            "annualSavingPercentage": -100.4,
            "annualStandingChargeElec": 18905.25,
            "annualStandingChargeGas": 10800.3,
            "contractLength": 26,
            "energySwitchGuarantee": False,
            "exitPenaltyAmount": 150.0,
            "saleable": False,
            "supplierName": "ScottishPower",
            "tariffEndDatePeriodFixed": "2026-05-31",
            "tariffEndDatePeriodRolling": 0,
            "tariffEndDateType": "F",
            "tariffName": "Help Beat Cancer Green Flexi May 2026 CM1 Online",
            "unitPriceElec": 24.829,
            "unitPriceGas": 6.183,
            "warmHomeDiscount": True
        },
        {
            "annualCost": 1759.12,
            "annualSaving": -881.49,
            "annualSavingPercentage": -100.4,
            "annualStandingChargeElec": 18905.25,
            "annualStandingChargeGas": 10800.3,
            "contractLength": 26,
            "energySwitchGuarantee": False,
            "exitPenaltyAmount": 150.0,
            "saleable": False,
            "supplierName": "ScottishPower",
            "tariffEndDatePeriodFixed": "2026-05-31",
            "tariffEndDatePeriodRolling": 0,
            "tariffEndDateType": "F",
            "tariffName": "Help Beat Cancer Green Flexi SR May 2026 DM1 Online",
            "unitPriceElec": 24.829,
            "unitPriceGas": 6.183,
            "warmHomeDiscount": True
        },
        {
            "annualCost": 1765.84,
            "annualSaving": -888.21,
            "annualSavingPercentage": -101.2,
            "annualStandingChargeElec": 18905.25,
            "annualStandingChargeGas": 10803.45,
            "contractLength": 24,
            "energySwitchGuarantee": False,
            "exitPenaltyAmount": 300.0,
            "saleable": False,
            "supplierName": "E.ON Next",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 24,
            "tariffEndDateType": "R",
            "tariffName": "Next Fixed 24m v8",
            "unitPriceElec": 24.126,
            "unitPriceGas": 6.409,
            "warmHomeDiscount": False
        },
        {
            "annualCost": 1771.17,
            "annualSaving": -893.54,
            "annualSavingPercentage": -101.8,
            "annualStandingChargeElec": 18905.25,
            "annualStandingChargeGas": 10803.45,
            "contractLength": 12,
            "energySwitchGuarantee": False,
            "exitPenaltyAmount": 150.0,
            "saleable": False,
            "supplierName": "E.ON Next",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 12,
            "tariffEndDateType": "R",
            "tariffName": "Next Fixed 12m v9",
            "unitPriceElec": 24.218,
            "unitPriceGas": 6.431,
            "warmHomeDiscount": False
        },
        {
            "annualCost": 1777.18,
            "annualSaving": -899.55,
            "annualSavingPercentage": -102.5,
            "annualStandingChargeElec": 14444.85,
            "annualStandingChargeGas": 11569.95,
            "contractLength": 24,
            "energySwitchGuarantee": False,
            "exitPenaltyAmount": 300.0,
            "saleable": False,
            "supplierName": "Ecotricity",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 24,
            "tariffEndDateType": "R",
            "tariffName": "2 Year Fixed Tariff V24.1",
            "unitPriceElec": 27.416,
            "unitPriceGas": 6.017,
            "warmHomeDiscount": True
        },
        {
            "annualCost": 1791.86,
            "annualSaving": -914.23,
            "annualSavingPercentage": -104.2,
            "annualStandingChargeElec": 18907.35,
            "annualStandingChargeGas": 10804.5,
            "contractLength": 12,
            "energySwitchGuarantee": True,
            "exitPenaltyAmount": 150.0,
            "saleable": True,
            "supplierName": "So Energy",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 12,
            "tariffEndDateType": "R",
            "tariffName": "So Nectarine One Year - Green",
            "unitPriceElec": 25.1,
            "unitPriceGas": 6.39,
            "warmHomeDiscount": True
        },
        {
            "annualCost": 1797.57,
            "annualSaving": -919.94,
            "annualSavingPercentage": -104.8,
            "annualStandingChargeElec": 18905.25,
            "annualStandingChargeGas": 10803.45,
            "contractLength": 24,
            "energySwitchGuarantee": False,
            "exitPenaltyAmount": 300.0,
            "saleable": False,
            "supplierName": "Sainsbury's Energy",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 24,
            "tariffEndDateType": "R",
            "tariffName": "Sainsburys Fix and Reward Fixed 24m v8",
            "unitPriceElec": 24.681,
            "unitPriceGas": 6.539,
            "warmHomeDiscount": True
        },
        {
            "annualCost": 1802.9,
            "annualSaving": -925.27,
            "annualSavingPercentage": -105.4,
            "annualStandingChargeElec": 18905.25,
            "annualStandingChargeGas": 10803.45,
            "contractLength": 12,
            "energySwitchGuarantee": False,
            "exitPenaltyAmount": 150.0,
            "saleable": False,
            "supplierName": "Sainsbury's Energy",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 12,
            "tariffEndDateType": "R",
            "tariffName": "Sainsburys Fix and Reward Fixed 12m v9",
            "unitPriceElec": 24.774,
            "unitPriceGas": 6.561,
            "warmHomeDiscount": True
        },
        {
            "annualCost": 1878.39,
            "annualSaving": -1000.76,
            "annualSavingPercentage": -114.0,
            "annualStandingChargeElec": 17904.6,
            "annualStandingChargeGas": 9803.85,
            "contractLength": 23,
            "energySwitchGuarantee": True,
            "exitPenaltyAmount": 400.0,
            "saleable": False,
            "supplierName": "British Gas",
            "tariffEndDatePeriodFixed": "2026-02-28",
            "tariffEndDatePeriodRolling": 0,
            "tariffEndDateType": "F",
            "tariffName": "Fixed Feb26 v2",
            "unitPriceElec": 27.941,
            "unitPriceGas": 6.592,
            "warmHomeDiscount": True
        },
        {
            "annualCost": 1878.39,
            "annualSaving": -1000.76,
            "annualSavingPercentage": -114.0,
            "annualStandingChargeElec": 17904.6,
            "annualStandingChargeGas": 9803.85,
            "contractLength": 24,
            "energySwitchGuarantee": True,
            "exitPenaltyAmount": 400.0,
            "saleable": False,
            "supplierName": "British Gas",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 24,
            "tariffEndDateType": "R",
            "tariffName": "The Fixed One 24M v5",
            "unitPriceElec": 27.941,
            "unitPriceGas": 6.592,
            "warmHomeDiscount": True
        },
        {
            "annualCost": 1932.42,
            "annualSaving": -1054.79,
            "annualSavingPercentage": -120.2,
            "annualStandingChargeElec": 18766.65,
            "annualStandingChargeGas": 5401.2,
            "contractLength": -1,
            "energySwitchGuarantee": False,
            "exitPenaltyAmount": 0.0,
            "saleable": False,
            "supplierName": "Outfox the Market",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 0,
            "tariffEndDateType": " ",
            "tariffName": "Fox Standard Dual",
            "unitPriceElec": 27.588,
            "unitPriceGas": 7.422,
            "warmHomeDiscount": False
        },
        {
            "annualCost": 1961.68,
            "annualSaving": -1084.05,
            "annualSavingPercentage": -123.5,
            "annualStandingChargeElec": 18905.25,
            "annualStandingChargeGas": 10803.45,
            "contractLength": 18,
            "energySwitchGuarantee": False,
            "exitPenaltyAmount": 200.0,
            "saleable": False,
            "supplierName": "E.ON Next",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 18,
            "tariffEndDateType": "R",
            "tariffName": "Next Fixed 18m v1",
            "unitPriceElec": 27.551,
            "unitPriceGas": 7.214,
            "warmHomeDiscount": False
        },
        {
            "annualCost": 1972.37,
            "annualSaving": -1094.74,
            "annualSavingPercentage": -124.7,
            "annualStandingChargeElec": 18905.25,
            "annualStandingChargeGas": 10803.45,
            "contractLength": 18,
            "energySwitchGuarantee": False,
            "exitPenaltyAmount": 200.0,
            "saleable": False,
            "supplierName": "Sainsbury's Energy",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 18,
            "tariffEndDateType": "R",
            "tariffName": "Sainsburys Fix and Reward Fixed 18m v1",
            "unitPriceElec": 27.737,
            "unitPriceGas": 7.258,
            "warmHomeDiscount": True
        },
        {
            "annualCost": 2007.53,
            "annualSaving": -1129.9,
            "annualSavingPercentage": -128.7,
            "annualStandingChargeElec": 18654.3,
            "annualStandingChargeGas": 10552.5,
            "contractLength": -1,
            "energySwitchGuarantee": False,
            "exitPenaltyAmount": 0.0,
            "saleable": False,
            "supplierName": "Utility Warehouse",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 0,
            "tariffEndDateType": " ",
            "tariffName": "Value",
            "unitPriceElec": 28.44,
            "unitPriceGas": 7.422,
            "warmHomeDiscount": True
        },
        {
            "annualCost": 2011.17,
            "annualSaving": -1133.54,
            "annualSavingPercentage": -129.2,
            "annualStandingChargeElec": 18902.1,
            "annualStandingChargeGas": 10800.3,
            "contractLength": -1,
            "energySwitchGuarantee": False,
            "exitPenaltyAmount": 0.0,
            "saleable": False,
            "supplierName": "OVO energy",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 0,
            "tariffEndDateType": " ",
            "tariffName": "Simpler Energy",
            "unitPriceElec": 28.434,
            "unitPriceGas": 7.413,
            "warmHomeDiscount": True
        },
        {
            "annualCost": 2012.55,
            "annualSaving": -1134.92,
            "annualSavingPercentage": -129.3,
            "annualStandingChargeElec": 18905.25,
            "annualStandingChargeGas": 10803.45,
            "contractLength": -1,
            "energySwitchGuarantee": True,
            "exitPenaltyAmount": 0.0,
            "saleable": False,
            "supplierName": "British Gas",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 0,
            "tariffEndDateType": " ",
            "tariffName": "Standard Variable",
            "unitPriceElec": 28.44,
            "unitPriceGas": 7.422,
            "warmHomeDiscount": True
        },
        {
            "annualCost": 2012.55,
            "annualSaving": -1134.92,
            "annualSavingPercentage": -129.3,
            "annualStandingChargeElec": 18905.25,
            "annualStandingChargeGas": 10803.45,
            "contractLength": -1,
            "energySwitchGuarantee": False,
            "exitPenaltyAmount": 0.0,
            "saleable": False,
            "supplierName": "E.ON Next",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 0,
            "tariffEndDateType": " ",
            "tariffName": "Next Flex",
            "unitPriceElec": 28.44,
            "unitPriceGas": 7.422,
            "warmHomeDiscount": False
        },
        {
            "annualCost": 2012.55,
            "annualSaving": -1134.92,
            "annualSavingPercentage": -129.3,
            "annualStandingChargeElec": 18905.25,
            "annualStandingChargeGas": 10803.45,
            "contractLength": -1,
            "energySwitchGuarantee": False,
            "exitPenaltyAmount": 0.0,
            "saleable": False,
            "supplierName": "Sainsbury's Energy",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 0,
            "tariffEndDateType": " ",
            "tariffName": "Sainsbury's Standard Variable",
            "unitPriceElec": 28.44,
            "unitPriceGas": 7.422,
            "warmHomeDiscount": True
        },
        {
            "annualCost": 2028.62,
            "annualSaving": -1150.99,
            "annualSavingPercentage": -131.1,
            "annualStandingChargeElec": 18725.7,
            "annualStandingChargeGas": 9063.6,
            "contractLength": 12,
            "energySwitchGuarantee": False,
            "exitPenaltyAmount": 96.0,
            "saleable": False,
            "supplierName": "Rebel Energy",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 12,
            "tariffEndDateType": "R",
            "tariffName": "Puffin Standard Direct",
            "unitPriceElec": 29.908,
            "unitPriceGas": 7.362,
            "warmHomeDiscount": False
        },
        {
            "annualCost": 2055.91,
            "annualSaving": -1178.28,
            "annualSavingPercentage": -134.3,
            "annualStandingChargeElec": 18905.25,
            "annualStandingChargeGas": 10803.45,
            "contractLength": -1,
            "energySwitchGuarantee": False,
            "exitPenaltyAmount": 0.0,
            "saleable": False,
            "supplierName": "Tulo Energy",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 0,
            "tariffEndDateType": " ",
            "tariffName": "SVT",
            "unitPriceElec": 29.936,
            "unitPriceGas": 7.422,
            "warmHomeDiscount": False
        },
        {
            "annualCost": 2086.11,
            "annualSaving": -1208.48,
            "annualSavingPercentage": -137.7,
            "annualStandingChargeElec": 22643.25,
            "annualStandingChargeGas": 10773.0,
            "contractLength": -1,
            "energySwitchGuarantee": False,
            "exitPenaltyAmount": 0.0,
            "saleable": False,
            "supplierName": "Rebel Energy",
            "tariffEndDatePeriodFixed": None,
            "tariffEndDatePeriodRolling": 0,
            "tariffEndDateType": " ",
            "tariffName": "Wren 1.0 EPG 6",
            "unitPriceElec": 29.568,
            "unitPriceGas": 7.454,
            "warmHomeDiscount": False
        }
    ]


def get_tariffs():
    return json.dumps(json_res())


def tariffs_schema():
    return {
        "type": "function",
        "function": {
            "name": "get_tariffs",
            "description": "Get available energy tariffs",
            "parameters": {},
        },
    }
